apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-orchestrator

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-orchestrator

  template:
    metadata:
      labels:
        app: ai-orchestrator

    spec:
      containers:

        - name: ai-orchestrator

          image: 192.168.49.1:5000/smartdeliveryops-ai-orchestrator:day15

          imagePullPolicy: Always

          ports:
            - containerPort: 8004

          env:

            - name: AI_MODEL_URL
              value: "http://ai-model-service:8003"

            - name: AI_PREDICTION_URL
              value: "http://ai-prediction-service:8002"

          resources:

            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service

metadata:
  name: ai-orchestrator-service

spec:
  selector:
    app: ai-orchestrator

  ports:

    - protocol: TCP
      port: 8004
      targetPort: 8004

  type: ClusterIP
