apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-prediction
  labels:
    app: ai-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-prediction
  template:
    metadata:
      labels:
        app: ai-prediction
    spec:
      containers:
        - name: ai-prediction
          image: 192.168.49.2:5000/smartdeliveryops-ai-prediction:build-8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 20
