apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: smartdeliveryops
  POSTGRES_USER: smartdelivery
  POSTGRES_PASSWORD: CHANGE_ME
  DATABASE_URL: postgresql://smartdelivery:CHANGE_ME@postgres-service:5432/smartdeliveryops
