apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - routes/frontend-route.yaml
  - routes/backend-route.yaml

labels:
  - pairs:
      app: smartdeliveryops
      managed-by: openshift
